### ISSUE TITLE
Default to the most recent "Publishing" target when deploying to GCE Windows VM

### ISSUE THREAD

**Issue by jsimonweb** [GoogleCloudPlatform/google-cloud-visualstudio#688] opened 2017-06-12 23:38 UTC
After using the Google Cloud Visual Studio extension to deploy an application to a GCE VM, it would be helpful to have that VM become the default publishing option when "Publish to Google Cloud" is subsequently selected in Visual Studio.

Testing this with two available GCE Windows VMs it appear that the Google Cloud Visual Studio extension consistently defaults to the VM that appears first based on alphabetical order.

**Comment by ivannaranjo** [comment] 2017-06-19 15:44
That is correct, the VMs are sorted by name and we choose the first one. Adding this to the M3 backlog to fix this.

**Comment by ILMTitan** [comment] 2018-05-09 23:53
This is a sub-issue of #863

**Comment by ILMTitan** [comment] 2018-05-10 17:29
Duplicate of #480

**Closed by ILMTitan** 2018-05-10 17:29 UTC
Labels: P1, enhancement
