### ISSUE TITLE
Failed to establish Remote PowerShell connection

### ISSUE THREAD

**Issue by iantalarico** [GoogleCloudPlatform/google-cloud-visualstudio#932] opened 2018-04-12 16:47 UTC
I am unable to attach a debugger.

Using:
- VS Professional 2017 v15.6.6
- Google Cloud Tools for VS: 1.2.100

Steps:
- Create a GCP windows VM instance
- Open VS and then the GCP extension.
- Find your project and windows VM instance
- Try to "Attach debugger"

This will fail with "Failed to establish Remote PowerShell connection"

**Comment by ILMTitan** [comment] 2018-06-26 21:19
I need to double check from home, but this looks like an issue with Google Corporate network policies disallowing the creation of PSSessions. I'm updating the error messages to make this more clear.

**Comment by iantalarico** [comment] 2018-06-26 21:23
@ILMTitan Now that you mention this I think I remember this being an issue.

**Comment by ILMTitan** [comment] 2018-06-28 20:51
Confirmed that my home computer was able to attach the debugger (after a fixing #1011). Closing.

**Comment by iantalarico** [comment] 2018-06-28 20:57
Should we make some note, reminder or comment somewhere so if I forget about this again we know why?

**Comment by ILMTitan** [comment] 2018-07-10 22:33
We should be able to search for this issue, even after it is closed.

**Closed by ILMTitan** 2018-07-10 22:33 UTC
Labels: P2, bug
