### ISSUE TITLE
There's no way to refresh the list of projects in the cloud explorer

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/google-cloud-visualstudio#203] opened 2016-09-26 22:42 UTC
except closing and re-opening VS. In fact, there's not even a way to logout of an existing account so that I can log back in again and that would refresh things.

**Comment by ivannaranjo** [comment] 2016-09-27 14:15
You can logout of an account by using the "Manage Accounts" dialog available from "Tools > Google Cloud Tools > Manage Accounts...". From the dialog you can delete accounts.

Dupe of #177 to add UI to refresh projects.

**Closed by ivannaranjo** 2016-09-27 14:15 UTC
