### ISSUE TITLE
Offer Google Cloud project templates in Visual C#, Web and Cloud nodes

### ISSUE THREAD

**Issue by YnR** [GoogleCloudPlatform/google-cloud-visualstudio#83] opened 2016-06-06 14:51 UTC
**CURRENT**
Google Cloud project templates are only offered in a Google Cloud node under Visual C#. most participants in our study missed it and went straight for the project templates in Web, Cloud or directly in Visual C# nodes.

**Comment by ivannaranjo** [comment] 2016-08-17 09:31
Duplicate of #113

**Closed by ivannaranjo** 2016-08-17 09:31 UTC
