### ISSUE TITLE
GCP Core template (MVC) fails to deploy because of Bower dependencies.

### ISSUE THREAD

**Issue by amanda-tarafa** [GoogleCloudPlatform/google-cloud-visualstudio#1028] opened 2018-07-16 12:18 UTC
The GCP Core template (MVC) fails out of the box publishing to GKE at least because of Bower dependencies. 

```
Deploying GcpCoreProject1 to Kubernetes Engine
dotnet publish -o "C:\Users\atarafamas\AppData\Local\Temp\n1x4hu0x.gwk" -c Release
Microsoft (R) Build Engine version 15.7.179.6572 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 66.1 ms for C:\Users\atarafamas\Documents\Visual Studio 2017\Projects\LibGeneralTesting\GcpCoreProject1\GcpCoreProject1.csproj.
  Restore completed in 35.35 ms for C:\Users\atarafamas\Documents\Visual Studio 2017\Projects\LibGeneralTesting\GcpCoreProject1\GcpCoreProject1.csproj.
  GcpCoreProject1 -> C:\Users\atarafamas\Documents\Visual Studio 2017\Projects\LibGeneralTesting\GcpCoreProject1\bin\Release\netcoreapp2.0\GcpCoreProject1.dll
  bower jquery-validation#1.14.0 EINVRES Request to https://bower.herokuapp.com/packages/jquery-validation failed with 502
C:\Users\atarafamas\Documents\Visual Studio 2017\Projects\LibGeneralTesting\GcpCoreProject1\GcpCoreProject1.csproj(23,5): error MSB3073: The command "bower install" exited with code 1.
Failed to deploy GcpCoreProject1 to Kubernetes Engine
```
Bower dependencies are not installed and apparently the restore is failing:
![image](https://user-images.githubusercontent.com/14878252/42757849-60071dd2-88f9-11e8-93b8-98e96390d891.png)

Even if I run the template locally is evident that none of these dependencies are being included:
![image](https://user-images.githubusercontent.com/14878252/42757931-a7c8e07e-88f9-11e8-91d3-8a906f0293f1.png)

If I try to install the dependencies by myself then I get the following error from the bower server:
```
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\cmd;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\Bower.cmd" install --force-latest
bower jquery-validation-unobtrusive#3.2.6          EINVRES Request to https://bower.herokuapp.com/packages/jquery-validation-unobtrusive failed with 502
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\cmd;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\Bower.cmd" install --force-latest
bower jquery-validation-unobtrusive#3.2.6          EINVRES Request to https://bower.herokuapp.com/packages/jquery-validation-unobtrusive failed with 502
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\cmd;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\Bower.cmd" install bootstrap#v4.1.2 --force-latest --save
bower jquery-validation-unobtrusive#3.2.6          EINVRES Request to https://bower.herokuapp.com/packages/jquery-validation-unobtrusive failed with 502

```
I don't know if our dependencies are outdated or bower is not working? I don't think we should ship a template with these issues.

I just edited the bower.json file and removed all the dependencies so I can deploy it.

**Comment by ILMTitan** [comment] 2018-07-16 16:13
Duplicate of #1013

**Closed by ILMTitan** 2018-07-16 16:13 UTC
Labels: duplicate, templates
