### ISSUE TITLE
Deploy never shows destination project in UI

### ISSUE THREAD

**Issue by benwulfe** [GoogleCloudPlatform/google-cloud-visualstudio#784] opened 2017-08-17 17:21 UTC
REPRO:

1. Deploy a new Web project using Google Cloud Tools for VS
2. Choose "Flex" and click "Publish"

RESULT:
Deploy succeeded!  Great!  but where did it go?  -- it went to the currently selected project in the Google Cloud Window -- which wasn't even showing.

I expected at some point to be asked or told where these bits were going as this could end up doing something very bad, like overwriting prod.

**Comment by Deren-Liao** [comment] 2017-08-17 18:12
I see your point now.  What exact information you'd like it to show?

I have some specific example here -- from your suggestion:

   - Show the to-be "URL" in this dialog.
   - Show deploy as "default" service
   - Show the project name





From Ben:

Definitely the project name.
The final URL is also useful.

**Comment by ivannaranjo** [comment] 2017-08-17 18:46
Makes sense. We can add a new dialog step with that information, which will
also be the last confirmation before publishing the app.

**Comment by ivannaranjo** [comment] 2017-10-06 14:08
Dupe of #486

**Closed by ivannaranjo** 2017-10-06 14:08 UTC
